# Generated by Django 2.1.5 on 2020-02-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20200217_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(upload_to='', verbose_name='media/'),
        ),
    ]
